site_name: Rare Disease Project Documentation
theme: readthedocs
nav:
  - index.md
  - installation.md
  - customization.md
  - service-accounts.md
  - deployment.md
  - migration.md
  - api.md
  - release-notes.md
