package ubc.pavlab.rdp.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Map;
import java.util.Set;

@Data
//@AllArgsConstructor
//@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class UserUpdatedProfileModel {
    @JsonProperty("email")
    private String email;
    private Profile profile;
    private Set<String> organUberonIds;
    private Map<String, TaxonGenesPayload> taxonGenesPayload;

    // No-args constructor, getters, and setters are generated by Lombok
}
